"""
Execution Runtime — Applies user-approved code to the live workbook data.

Critical invariant: this module ONLY executes code that has been:
1. Generated by the code engine
2. Validated by the AST safety validator
3. Dry-run previewed and explicitly approved by the user

The runtime re-executes the SAME validated code — it never re-generates,
guaranteeing that what was approved is what runs.
"""

from __future__ import annotations

import logging
from typing import Optional

import numpy as np
import pandas as pd

from backend.models.schemas import ExecutionResult

logger = logging.getLogger(__name__)


class ExecutionRuntime:
    """
    Applies validated, user-approved code to the live DataFrame.
    Maintains execution history for audit trail.
    """

    SAFE_BUILTINS = {
        "len": len,
        "round": round,
        "sum": sum,
        "min": min,
        "max": max,
        "abs": abs,
        "int": int,
        "float": float,
        "str": str,
        "bool": bool,
        "list": list,
        "dict": dict,
        "tuple": tuple,
        "set": set,
        "sorted": sorted,
        "reversed": reversed,
        "enumerate": enumerate,
        "zip": zip,
        "range": range,
        "isinstance": isinstance,
        "type": type,
        "print": print,
        "True": True,
        "False": False,
        "None": None,
    }

    def __init__(self):
        self._execution_count = 0

    def execute(
        self,
        code: str,
        df: pd.DataFrame,
    ) -> tuple[ExecutionResult, pd.DataFrame]:
        """
        Execute approved code against the live DataFrame.
        
        Args:
            code: The SAME validated code from the dry-run (never re-generated)
            df: The live DataFrame to modify
            
        Returns:
            Tuple of (ExecutionResult, result_df)
        """
        original_rows = len(df)

        local_ns = {
            "df": df,
            "pd": pd,
            "np": np,
        }

        try:
            exec(code, {"__builtins__": self.SAFE_BUILTINS}, local_ns)
        except Exception as e:
            logger.error(f"Live execution failed: {e}")
            return ExecutionResult(
                success=False,
                rows_affected=0,
                message=f"Execution failed: {type(e).__name__}: {e}",
                result_preview=[],
            ), df

        result_df = local_ns.get("result")
        if result_df is None:
            result_df = local_ns.get("df", df)

        if isinstance(result_df, pd.Series):
            result_df = result_df.to_frame()
        elif not isinstance(result_df, pd.DataFrame):
            result_df = pd.DataFrame({"result": [result_df]})

        rows_affected = abs(len(result_df) - original_rows) or len(result_df)
        self._execution_count += 1

        # Build preview (first 20 rows)
        preview = []
        for _, row in result_df.head(20).iterrows():
            record = {}
            for col in result_df.columns:
                val = row[col]
                if val is None or (isinstance(val, float) and np.isnan(val)):
                    record[str(col)] = None
                else:
                    record[str(col)] = str(val)
            preview.append(record)

        return ExecutionResult(
            success=True,
            rows_affected=rows_affected,
            message=f"Successfully executed. Result has {len(result_df)} rows × {len(result_df.columns)} columns.",
            result_preview=preview,
        ), result_df
